@base = http://localhost:3001


###
POST {{base}}/accounts
Content-Type: application/json

{
    "owner":"adjyth",
    "currency":"USD"
}


###

GET {{base}}/accounts/3

###

GET {{base}}/accounts?page_id=1&page_size=5

### 
POST  {{base}}/transfers
Content-Type: application/json

{
    "from_account_id":1,
    "to_account_id":2,
    "amount":10,
    "currency":"CADs"
}

### 
POST  {{base}}/users
Content-Type: application/json

{
    "username":"hung2",
    "full_name":"Hung Nguyen",
    "email":"hungnguyen2@gmail.com",
    "password":"123123"
}


###
POST {{base}}/users/login
Content-Type: application/json

{
    "username":"hundfgg2",
    "password":"123s123"
}